### ISSUE TITLE
User access Level?

### ISSUE THREAD

**Issue by ottafish** [timhaintz/timhaintz.github.io#1]
Thanks Tim. Great tip. 
Can I ask, what  AD user access level does a person need to be when using the commands as described from a Windows 10 PC?

**Comment by timhaintz** [comment]
Thanks for the question @ottafish. First one! I have found that read-only access works with most of the Get verbs. For Set verbs, you will most likely need Administrator access. From [Get-ADComputer](https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-adcomputer?view=winserver2012-ps) "If the acting credentials do not have directory-level permission to perform the task, Active Directory PowerShell returns a terminating error." You can use the -Credential parameter if you would like to use an account that has escalated privileges. 
Hope this helps.
