### ISSUE TITLE
Piping the report?

### ISSUE THREAD

**Issue by ottafish** [timhaintz/timhaintz.github.io#2]
Hi Tim,
Great post. Good reading and I've already copied the code.
I would like to ask, can I use 'Send-MailMessage' to email me the report as either an attachment, or as a HTML formatted email body?

If it's possible, I'd love an idea of how to do that.
Again, thanks

**Comment by timhaintz** [comment]
Great question. Will look into it and update the blog post. When I do, will let you know. Thanks for reading and the feedback @ottafish

**Comment by timhaintz** [comment]
Hi again @ottafish . Please see update [here](https://timhaintz.github.io/blog/2018/05/31/Generating-a-HTML-report-of-your-servers). Thanks, Tim.
